version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.8
    
    dependencies:
      pre:
        - sudo apt-get update; sudo apt-get install -y libgl1-mesa-dev xorg-dev
      
    working_directory: /go/src/github.com/krstenjacobs/8080-go
    steps:
      - checkout
      - run: make
      - run: make test
      - run: make run-test

