version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
      
    working_directory: /go/src/github.com/kristenjacobs/8080-go
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: sudo apt-get update ; sudo apt-get install -y libgl1-mesa-dev xorg-dev
      - run: 
          name: Build
          command: make
      - run: 
          name: Unit Test
          command: make test
      - run: 
          name: Core Test
          command: make run-test

