version: 2

dependencies:
  pre:
    - sudo apt-get update; sudo apt-get install -y libgl1-mesa-dev xorg-dev
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      
    working_directory: /go/src/github.com/kristenjacobs/8080-go
    steps:
      - checkout
      - run: make
      - run: make test
      - run: make run-test

